version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: pwbclassification-db
    restart: always
    environment:
      - MYSQL_DATABASE=pwbclassification
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pwbclassification-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  pwbclassification-data:
    driver: local
